Discord:
  Auth: # $CONF_DISCORD_AUTH
  Guilds: [ 910284757072502805 ]
  Channels: [ 910284757072502808 ]

Posts:
  IgnoreRegexp: nopost

Storage:
  PostgresDSN: # $CONF_STORAGE_POSTGRESDSN

Logging:
  Level: debug