Discord:
  Auth: # $CONF_DISCORD_AUTH
  Guilds: [ 000000000000000000 ]
  Channels: [ 000000000000000000 ]

Posts:
  IgnoreRegexp: nopost

Storage:
  PostgresDSN: # $CONF_STORAGE_POSTGRESDSN

Logging:
  Level: debug

Api:
  Port: 8081